ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ org.taskhub.server.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/taskhub"
    url = ${?DATABASE_URL}
    user = "taskhub"
    user = ${?DATABASE_USER}
    password = "taskhub"
    password = ${?DATABASE_PASSWORD}
}
